# Site settings
title: Your friend 당신의 친구 
email: taeyoon@sfpc.io
description: > # letters and collaboration with artist friends
baseurl: "/yourfriend" # the subpath of your site, e.g. /blog/
url: "http://taeyoonchoi.com/yourfriend" # the base hostname & protocol for your site
twitter_username: tchoi8
github_username:  tchoi8

# Build settings
markdown: kramdown
